name: Deploy attached build to Cloudflare Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download release asset
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          version: tags/${{ github.event.release.tag_name }}
          file: 'dist.tar.gz'
          target: 'dist.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create dist directory
        run: mkdir -p dist
      - name: Extract asset
        run: tar -xzf dist.tar.gz -C dist
      - name: Upload to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          projectName: ${{ vars.CF_PROJECT_NAME }}
          directory: ./dist
