name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Yarn
        run: npm install -g yarn
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install modules
        run: yarn install
      - name: Linting
        run: |
          yarn run lint
      - name: Coverage
        run: |
          yarn run test:unit --run
